{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}

--  Generated by AI

-- | End-to-end integration tests that run each handler against a real
--   PostgreSQL database
--
--   The suite spins up a connection pool to the database specified by the
--   @TEST_DATABASE_URL@ environment variable, runs @migrateAll@ and all
--   legacy migrations before each test group, and cleans every table
--   before each individual test via @cleanDatabase@.
--
--   Covered features:
--
--   * __Memories__     — full CRUD, soft-delete and restore, 404 on missing id,
--                        400 for invalid input \/ unsafe filenames \/ reversed date range
--   * __Relationship__ — profile creation with defaults, side-key validation,
--                        display-name anonymisation, computed counters (days together,
--                        anniversary, monthiversary)
--   * __Notes__        — full CRUD, restore, owner stability across profile renames,
--                        legacy display-name migration, duplicate-title 400
--   * __Plans__        — category normalisation, bulk category rename \/ delete,
--                        trash and restore
--   * __Important days__ — CRUD, restore, 400 for blank title, 404 on missing id,
--                          legacy @"anniversary"@ trash-kind migration
--   * __Memory bulk ops__ — tag and location catalog sync from existing memories
--   * __Diary__        — CRUD, 404 on missing id, future-date rejection (400)
module Handler.IntegrationSpec (spec) where

import Control.Monad.Logger (runNoLoggingT)
import Control.Monad.Reader (runReaderT)
import Data.ByteString.Char8 (pack)
import Data.List (isSuffixOf)
import Data.Maybe (fromJust, isJust)
import Data.Time (UTCTime, getCurrentTime)
import Database.Persist
import Database.Persist.Postgresql (ConnectionPool, createPostgresqlPool)
import Database.Persist.Sql (runMigrationUnsafe, runSqlPool)
import Handler.Diary
import Handler.Helpers (AppM)
import Handler.ImportantDays
import Handler.Memories
import Handler.Notes
import Handler.Plans
import Handler.Relationship
import Handler.Tags
import Handler.Trash
import Models
import Servant (NoContent (..), ServerError (..), runHandler)
import System.Environment (lookupEnv)
import Test.Hspec
import TestHelpers (atDay)
import Types

spec :: Spec
spec =
  beforeAll setupPool $ do
    describe "memory handlers with database persistence" $ do
      it "creates, fetches, filters, deletes and restores a memory" $ \mPool ->
        withPool mPool $ \pool -> do
          row <- runAppSuccess pool (createMemory sampleMemory)

          mrTitle row `shouldBe` "First trip"
          mrTags row `shouldBe` ["summer", "trip"]
          mrPhotos row `shouldBe` ["one.jpg", "two.jpg"]

          fetched <- runAppSuccess pool (getMemory (mrId row))
          fetched `shouldBe` row

          filtered <- runAppSuccess pool (listMemories (Just "trip") Nothing Nothing Nothing Nothing)
          map mrId filtered `shouldBe` [mrId row]

          _ <- runAppSuccess pool (deleteMemory (mrId row))
          runAppStatus pool (getMemory (mrId row)) `shouldReturn` 404

          trash <- runAppSuccess pool listTrash
          map trKind trash `shouldBe` ["memory"]
          map trName trash `shouldBe` ["First trip"]

          case trash of
            [item] ->
              runAppSuccess pool (restoreTrashItem (trId item)) >>= (`shouldBe` NoContent)
            _ ->
              expectationFailure "Expected exactly one trash item."

          restored <- runAppSuccess pool (listMemories Nothing Nothing Nothing Nothing Nothing)
          map mrTitle restored `shouldBe` ["First trip"]

      it "returns 404 for a missing memory" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (getMemory 999999) `shouldReturn` 404

      it "returns 400 for invalid memory input" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (createMemory sampleMemory {miTitle = " "}) `shouldReturn` 400

      it "returns 400 for unsafe memory photo filenames" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (createMemory sampleMemory {miPhotos = ["../secret.jpg"]}) `shouldReturn` 400

      it "returns 400 for a reversed date filter range" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus
            pool
            (listMemories Nothing Nothing Nothing (Just "2026-02-01") (Just "2026-01-01"))
            `shouldReturn` 400

      it "returns 404 when updating a nonexistent memory" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (updateMemory 999999 sampleMemory) `shouldReturn` 404

    describe "relationship handlers with computed backend data" $ do
      it "creates unnamed profiles until the user supplies a name" $ \mPool ->
        withPool mPool $ \pool -> do
          left <- runAppSuccess pool (getProfile "left")
          right <- runAppSuccess pool (getProfile "right")

          prName left `shouldBe` ""
          prName right `shouldBe` ""

      it "rejects arbitrary profile sides without creating a row" $ \mPool ->
        withPool mPool $ \pool -> do
          runAppStatus pool (getProfile "middle") `shouldReturn` 400
          invalidRows <- runSqlPool (count [PersonProfileDbSide ==. "middle"]) pool
          invalidRows `shouldBe` 0

      it "persists relationship settings and returns computed counters" $ \mPool ->
        withPool mPool $ \pool -> do
          saved <- runAppSuccess pool (putRelationship sampleRelationship)

          rrStartDate saved `shouldBe` Just relationshipStart
          rrHeartColor saved `shouldBe` "heart-blue"
          rrDaysTogether saved `shouldSatisfy` isJust
          rrNextAnniversary saved `shouldSatisfy` isJust
          rrNextMonthiversary saved `shouldSatisfy` isJust
          rrAnniversaryDays saved `shouldSatisfy` isJust
          rrMonthiversaryDays saved `shouldSatisfy` isJust

          fetched <- runAppSuccess pool getRelationshipRow
          rrStartDate fetched `shouldBe` Just relationshipStart
          rrHeartColor fetched `shouldBe` "heart-blue"

    describe "note handlers with database persistence" $ do
      it "creates, updates, deletes and restores a note" $ \mPool ->
        withPool mPool $ \pool -> do
          created <- runAppSuccess pool (createNote sampleNote)
          nrOwner created `shouldBe` "left"
          nrTitle created `shouldBe` "Gift idea"

          runAppSuccess
            pool
            (updateNote (nrId created) sampleNote {niTitle = "Updated gift", niBody = "Book"})
            >>= (`shouldBe` NoContent)

          updated <- runAppSuccess pool listNotes
          map nrTitle updated `shouldBe` ["Updated gift"]

          runAppSuccess pool (deleteNote (nrId created)) >>= (`shouldBe` NoContent)
          runAppSuccess pool listNotes >>= (`shouldBe` [])

          trash <- runAppSuccess pool listTrash
          map trKind trash `shouldBe` ["note"]
          map trName trash `shouldBe` ["Updated gift"]

          case trash of
            [item] ->
              runAppSuccess pool (restoreTrashItem (trId item)) >>= (`shouldBe` NoContent)
            _ ->
              expectationFailure "Expected exactly one trash item."

          restored <- runAppSuccess pool listNotes
          map nrTitle restored `shouldBe` ["Updated gift"]

      it "returns 400 for a blank note owner" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (createNote sampleNote {niOwner = "A"}) `shouldReturn` 400

      it "returns 404 when updating a nonexistent note" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (updateNote 999999 sampleNote) `shouldReturn` 404

      it "keeps note ownership stable when a profile name changes" $ \mPool ->
        withPool mPool $ \pool -> do
          _ <- runAppSuccess pool (createNote sampleNote)
          runAppSuccess pool (upsertPerson "left" "Renamed" "figure" Nothing "figure-red" "flower" "smile" Nothing)

          notes <- runAppSuccess pool listNotes
          map nrOwner notes `shouldBe` ["left"]

      it "returns 400 for duplicate note titles instead of a database error" $ \mPool ->
        withPool mPool $ \pool -> do
          first <- runAppSuccess pool (createNote sampleNote)
          conflictingNote <- runAppSuccess pool (createNote sampleNote {niTitle = "Other idea"})

          runAppStatus pool (createNote sampleNote) `shouldReturn` 400
          runAppStatus pool (updateNote (nrId conflictingNote) sampleNote) `shouldReturn` 400
          runAppSuccess pool (updateNote (nrId first) sampleNote) >>= (`shouldBe` NoContent)

    describe "plan handlers with database persistence" $ do
      it "normalises blank categories and supports category bulk operations" $ \mPool ->
        withPool mPool $ \pool -> do
          firstPlan <- runAppSuccess pool (createPlan samplePlan {piCategory = " "})
          completedPlan <- runAppSuccess pool (createPlan samplePlan {piTitle = "Done plan", piDone = True})

          prCategory firstPlan `shouldBe` "Other"
          prCategory completedPlan `shouldBe` "Travel"

          runAppSuccess pool (renamePlanCategory "Other" (RenameInput "Home")) >>= (`shouldBe` NoContent)

          afterRename <- runAppSuccess pool listPlans
          map prCategory afterRename `shouldBe` ["Home", "Travel"]

          runAppSuccess pool (deletePlanCategory "Travel" (DeleteCategoryInput (Just "done"))) >>= (`shouldBe` NoContent)

          afterScopedDelete <- runAppSuccess pool listPlans
          map prTitle afterScopedDelete `shouldBe` ["Visit museum"]

      it "moves deleted plans to trash and restores them" $ \mPool ->
        withPool mPool $ \pool -> do
          created <- runAppSuccess pool (createPlan samplePlan)
          runAppSuccess pool (deletePlan (prId created)) >>= (`shouldBe` NoContent)

          trash <- runAppSuccess pool listTrash
          map trKind trash `shouldBe` ["plan"]
          map trName trash `shouldBe` ["Visit museum"]

          case trash of
            [item] ->
              runAppSuccess pool (restoreTrashItem (trId item)) >>= (`shouldBe` NoContent)
            _ ->
              expectationFailure "Expected exactly one trash item."

          restored <- runAppSuccess pool listPlans
          map prTitle restored `shouldBe` ["Visit museum"]

      it "returns 404 when updating a nonexistent plan" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (updatePlan 999999 samplePlan) `shouldReturn` 404

    describe "important day handlers with database persistence" $ do
      it "creates, updates, deletes and restores a manual important day" $ \mPool ->
        withPool mPool $ \pool -> do
          created <- runAppSuccess pool (createImportantDay sampleImportantDay)
          idrTitle created `shouldBe` "First date"

          let createdId = fromJust (idrId created)
          runAppSuccess
            pool
            (updateImportantDay createdId sampleImportantDay {idiTitle = "First date updated"})
            >>= (`shouldBe` NoContent)

          updated <- runAppSuccess pool listImportantDays
          map idrTitle updated `shouldBe` ["First date updated"]

          runAppSuccess pool (deleteImportantDay createdId) >>= (`shouldBe` NoContent)
          runAppSuccess pool listImportantDays >>= (`shouldBe` [])

          trash <- runAppSuccess pool listTrash
          map trKind trash `shouldBe` ["important-day"]
          map trName trash `shouldBe` ["First date updated"]

          case trash of
            [item] ->
              runAppSuccess pool (restoreTrashItem (trId item)) >>= (`shouldBe` NoContent)
            _ ->
              expectationFailure "Expected exactly one trash item."

          restored <- runAppSuccess pool listImportantDays
          map idrTitle restored `shouldBe` ["First date updated"]

      it "returns 400 for a blank important day title" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (createImportantDay sampleImportantDay {idiTitle = " "}) `shouldReturn` 400

      it "returns 404 when updating a nonexistent important day" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (updateImportantDay 999999 sampleImportantDay) `shouldReturn` 404

    describe "memory bulk operations" $ do
      it "persists standalone catalog values without frontend state" $ \mPool ->
        withPool mPool $ \pool -> do
          runAppSuccess pool (createTag (CatalogInput "family")) >>= (`shouldBe` NoContent)
          runAppSuccess pool (createLocation (CatalogInput "Vienna")) >>= (`shouldBe` NoContent)
          runAppSuccess pool (createPlanCategory (CatalogInput "Concerts")) >>= (`shouldBe` NoContent)

          runAppSuccess pool listTags >>= (`shouldBe` ["family"])
          runAppSuccess pool listLocations >>= (`shouldBe` ["Vienna"])
          runAppSuccess pool listPlanCategories >>= (`shouldBe` ["Concerts"])

      it "renames and deletes tags and locations across memories" $ \mPool ->
        withPool mPool $ \pool -> do
          row <- runAppSuccess pool (createMemory sampleMemory)

          runAppSuccess pool (renameTag "trip" (RenameInput "journey")) >>= (`shouldBe` NoContent)
          runAppSuccess pool (renameLocation "Prague" (RenameInput "Brno")) >>= (`shouldBe` NoContent)

          renamed <- runAppSuccess pool (getMemory (mrId row))
          mrTags renamed `shouldBe` ["journey", "summer"]
          mrLocation renamed `shouldBe` Just "Brno"
          runAppSuccess pool listTags >>= (`shouldBe` ["journey", "summer"])
          runAppSuccess pool listLocations >>= (`shouldBe` ["Brno"])

          runAppSuccess pool (deleteTag "summer") >>= (`shouldBe` NoContent)
          runAppSuccess pool (deleteLocation "Brno") >>= (`shouldBe` NoContent)

          cleaned <- runAppSuccess pool (getMemory (mrId row))
          mrTags cleaned `shouldBe` ["journey"]
          mrLocation cleaned `shouldBe` Nothing

      it "rejects blank bulk rename targets" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (renameTag "trip" (RenameInput " ")) `shouldReturn` 400

      it "normalises whitespace in the old-name path parameter when renaming a tag" $ \mPool ->
        withPool mPool $ \pool -> do
          row <- runAppSuccess pool (createMemory sampleMemory)
          runAppSuccess pool (renameTag " trip " (RenameInput "journey")) >>= (`shouldBe` NoContent)
          renamed <- runAppSuccess pool (getMemory (mrId row))
          mrTags renamed `shouldSatisfy` elem "journey"
          mrTags renamed `shouldSatisfy` notElem "trip"

      it "merges tag renames when the target tag already exists on a memory" $ \mPool ->
        withPool mPool $ \pool -> do
          row <- runAppSuccess pool (createMemory sampleMemory {miTags = ["trip", "journey", "summer"]})

          runAppSuccess pool (renameTag "trip" (RenameInput "journey")) >>= (`shouldBe` NoContent)

          renamed <- runAppSuccess pool (getMemory (mrId row))
          mrTags renamed `shouldBe` ["journey", "summer"]

    describe "canonical important-day projection" $ do
      it "returns profile birthdays with explicit metadata" $ \mPool ->
        withPool mPool $ \pool -> do
          runAppSuccess pool (upsertPerson "left" "A" "figure" Nothing "figure-red" "flower" "smile" (Just birthdayDate))
          runAppSuccess pool (upsertPerson "right" "B" "figure" Nothing "figure-blue" "hat" "laugh" Nothing)

          rows <- runAppSuccess pool listImportantDays
          map idrKind rows `shouldBe` ["birthday"]
          map idrOwner rows `shouldBe` [Just "left"]
          map idrId rows `shouldBe` [Nothing]
          map idrTitle rows `shouldBe` ["A"]
          map idrMonth rows `shouldBe` [3]
          map idrDay rows `shouldBe` [15]
          map idrDaysUntil rows `shouldSatisfy` all (>= 0)

      it "does not mix relationship rows into important days" $ \mPool ->
        withPool mPool $ \pool -> do
          runAppSuccess pool (upsertRelationship (Just relationshipStart) "heart-blue")
          runAppSuccess pool listImportantDays >>= (`shouldBe` [])

    describe "trash edge cases" $ do
      it "returns 404 when restoring a nonexistent trash item" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (restoreTrashItem 999999) `shouldReturn` 404

      it "permanently deletes a trash item without restoring it" $ \mPool ->
        withPool mPool $ \pool -> do
          created <- runAppSuccess pool (createMemory sampleMemory)
          runAppSuccess pool (deleteMemory (mrId created)) >>= (`shouldBe` NoContent)
          trash <- runAppSuccess pool listTrash
          case trash of
            [item] -> do
              runAppSuccess pool (deleteTrashItemPermanent (trId item)) >>= (`shouldBe` NoContent)
              runAppSuccess pool listTrash >>= (`shouldSatisfy` null)
              runAppSuccess pool (listMemories Nothing Nothing Nothing Nothing Nothing)
                >>= (`shouldSatisfy` null)
            _ -> expectationFailure "Expected exactly one trash item."

      it "returns 400 when the trash payload cannot be decoded" $ \mPool ->
        withPool mPool $ \pool -> do
          now <- getCurrentTime
          runSqlPool (insert_ (TrashItemDb "memory" "not valid json" now)) pool
          trash <- runAppSuccess pool listTrash
          case trash of
            [item] ->
              runAppStatus pool (restoreTrashItem (trId item)) `shouldReturn` 400
            _ ->
              expectationFailure "Expected one trash item with a broken payload."

    describe "diary handlers with database persistence" $ do
      it "creates, updates, and deletes a diary entry" $ \mPool ->
        withPool mPool $ \pool -> do
          created <- runAppSuccess pool (createDiaryEntry sampleDiary)
          derOwner created `shouldBe` "left"
          derBody created `shouldBe` "First entry"

          runAppSuccess
            pool
            (updateDiaryEntry (derId created) sampleDiary {deiBody = "Updated entry"})
            >>= (`shouldBe` NoContent)

          updated <- runAppSuccess pool listDiaryEntries
          map derBody updated `shouldBe` ["Updated entry"]

          runAppSuccess pool (deleteDiaryEntry (derId created)) >>= (`shouldBe` NoContent)
          runAppSuccess pool listDiaryEntries >>= (`shouldSatisfy` null)

      it "returns 404 when updating a nonexistent diary entry" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (updateDiaryEntry 999999 sampleDiary) `shouldReturn` 404

      it "rejects invalid diary owners and blank entries" $ \mPool ->
        withPool mPool $ \pool -> do
          runAppStatus pool (createDiaryEntry sampleDiary {deiOwner = "shared"}) `shouldReturn` 400
          runAppStatus pool (createDiaryEntry sampleDiary {deiBody = "   "}) `shouldReturn` 400

      it "normalises diary owner and body before persistence" $ \mPool ->
        withPool mPool $ \pool -> do
          created <- runAppSuccess pool (createDiaryEntry sampleDiary {deiOwner = " LEFT ", deiBody = "  Entry  "})
          derOwner created `shouldBe` "left"
          derBody created `shouldBe` "Entry"

      it "returns 404 when deleting a nonexistent diary entry" $ \mPool ->
        withPool mPool $ \pool ->
          runAppStatus pool (deleteDiaryEntry 999999) `shouldReturn` 404

      it "lists entries from both owners" $ \mPool ->
        withPool mPool $ \pool -> do
          _ <- runAppSuccess pool (createDiaryEntry sampleDiary)
          _ <- runAppSuccess pool (createDiaryEntry sampleDiary {deiOwner = "right", deiBody = "Right entry"})
          entries <- runAppSuccess pool listDiaryEntries
          length entries `shouldBe` 2
          map derOwner entries `shouldSatisfy` (\owners -> "left" `elem` owners && "right" `elem` owners)

setupPool :: IO (Maybe ConnectionPool)
setupPool = do
  mUrl <- lookupEnv "TEST_DATABASE_URL"
  case mUrl of
    Nothing ->
      pure Nothing
    Just url
      | not (isSafeTestDatabaseUrl url) ->
          fail "TEST_DATABASE_URL must point to a database whose name ends with _test."
      | otherwise -> do
          pool <- runNoLoggingT (createPostgresqlPool (pack url) 2)
          runSqlPool (runMigrationUnsafe migrateAll) pool
          pure (Just pool)

isSafeTestDatabaseUrl :: String -> Bool
isSafeTestDatabaseUrl url =
  "_test" `isSuffixOf` databaseName
  where
    withoutQuery = takeWhile (/= '?') url
    databaseName = reverse (takeWhile (/= '/') (reverse withoutQuery))

withPool :: Maybe ConnectionPool -> (ConnectionPool -> Expectation) -> Expectation
withPool mPool action =
  case mPool of
    Nothing ->
      pendingWith "Set TEST_DATABASE_URL to a dedicated database ending in _test to run integration tests."
    Just pool -> do
      cleanDatabase pool
      action pool

runAppSuccess :: ConnectionPool -> AppM a -> IO a
runAppSuccess pool action =
  runHandler (runReaderT action pool) >>= \case
    Right value ->
      pure value
    Left err ->
      fail ("Expected success, got HTTP " <> show (errHTTPCode err))

runAppStatus :: ConnectionPool -> AppM a -> IO Int
runAppStatus pool action =
  runHandler (runReaderT action pool) >>= \case
    Right _ ->
      fail "Expected handler failure, got success."
    Left err ->
      pure (errHTTPCode err)

cleanDatabase :: ConnectionPool -> IO ()
cleanDatabase pool =
  runSqlPool
    ( do
        deleteWhere ([] :: [Filter MemoryPhotoDb])
        deleteWhere ([] :: [Filter MemoryTagDb])
        deleteWhere ([] :: [Filter MemoryDb])
        deleteWhere ([] :: [Filter TagCatalogDb])
        deleteWhere ([] :: [Filter LocationCatalogDb])
        deleteWhere ([] :: [Filter ImportantDayDb])
        deleteWhere ([] :: [Filter RelationshipDb])
        deleteWhere ([] :: [Filter PersonProfileDb])
        deleteWhere ([] :: [Filter CoupleNoteDb])
        deleteWhere ([] :: [Filter CouplePlanDb])
        deleteWhere ([] :: [Filter PlanCategoryDb])
        deleteWhere ([] :: [Filter DiaryEntryDb])
        deleteWhere ([] :: [Filter TrashItemDb])
    )
    pool

sampleMemory :: MemoryInput
sampleMemory =
  MemoryInput
    { miTitle = "First trip",
      miTimeFrom = atDay 2026 1 1,
      miTimeTo = atDay 2026 1 2,
      miDescription = Just "Nice holiday",
      miLocation = Just "Prague",
      miTags = ["trip", "summer", "trip"],
      miPhotos = ["one.jpg", "two.jpg", "one.jpg"]
    }

sampleRelationship :: RelationshipInput
sampleRelationship =
  RelationshipInput
    { riStartDate = Just relationshipStart,
      riHeartColor = "heart-blue"
    }

sampleNote :: NoteInput
sampleNote =
  NoteInput
    { niOwner = "left",
      niTitle = "Gift idea",
      niBody = "Flowers"
    }

samplePlan :: PlanInput
samplePlan =
  PlanInput
    { piCategory = "Travel",
      piTitle = "Visit museum",
      piDetail = Just "Book tickets",
      piDone = False
    }

sampleImportantDay :: ImportantDayInput
sampleImportantDay =
  ImportantDayInput
    { idiTitle = "First date",
      idiDate = atDay 2021 5 20,
      idiNote = Just "Dinner"
    }

sampleDiary :: DiaryInput
sampleDiary =
  DiaryInput
    { deiOwner = "left",
      deiDate = atDay 2026 6 21,
      deiBody = "First entry"
    }

relationshipStart :: UTCTime
relationshipStart =
  atDay 2020 6 15

birthdayDate :: UTCTime
birthdayDate =
  atDay 1990 3 15
